name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          host-url: 'http://localhost:9000'
          login: ${{ secrets.SONAR_TOKEN }}
